refactor: support sha512 hash from ChubbyAnt sedutil
open-source-firmware/go-tcg-storage pull request #114
Opened 2023-10-19 14:04 UTC by matfax

The sha512-based [sedutil fork](https://github.com/ChubbyAnt/sedutil) from ChubbyAnt has been out there since 2021. This refactors the library, gosedctl, and sedlockctl to support their sha512 hashing method. This allows migration from their sedutil to go-tcg-storage without a hassle.

In particular, the following changes have been made:
* Migrated the hashing method from `sedlockctl` to `pkg` for reuse in multiple cmds
* Added reusable sha512 method to hashing library
* Added kong flag for hashing method selection, adding sedutil-sha512 option
* Overhauled kong structures to avoid redundant boilerplate for hashing
* Use kong's file type checks where applicable
* Provide device as argument, not flag
* Passwords can be provided as environment variables
* Added stdin fallback for missing password flags
* Fixed some error handling issues
* Updated dependencies

This is a BREAKING CHANGE for cmds. `-p` short flags had to be removed from gosedctl because kong does neither support overriding embeedding configs nor does it prefix shorts when embedding.

2025-04-28 06:58 UTC, ChriMarMe approved these changes
Thank you for your contribution.

In general LGTM, but I have to see what the CI does. Haven't been involved in this repo for 2 years.

2025-04-28 07:08 UTC, ChriMarMe requested changes
I block this until we have a CI in place.

Working on that, and will let you know when we're done.

Sorry for the confusion.

2025-04-28 07:37 UTC, matfax commented
After that period, CI might even fail because of outdated dependencies. Let's halt this until I recheck everything.

2025-05-07 08:44 UTC, ChriMarMe commented
I updated the CI. Can you rebase?

2025-05-07 18:32 UTC, matfax commented
I've tested `sedlockctl` on a non-enterprise setup. However, I can't get `gosedctl` to work with my 970 Evo Plus. Param parsing, hashing and authentication are ok. But I'm ending in a `ErrTPerClosedSession`. ChubbyAnt's [sedutil fork](https://github.com/ChubbyAnt/sedutil) doesn't have the issue. I can only guess that it might be related to the chunk size or different versions. Nothing indicates to me that it would be introduced by these changes. It's nothing that I need resolved, just beware that I haven't thoroughly tested `gosedctl`. Proper CI testing of such features would be difficult. I hope you can test it before merging.

You may also squash my commit spam.

Lastly, just another reminder that this breaks the existing cli structure, so a minor or major version bump is advised.

2025-05-15 12:18 UTC, matfax commented on README.md
> +[![Workflow](https://github.com/open-source-firmware/go-tcg-storage/workflows/Go/badge.svg)](https://github.com/open-source-firmware/go-tcg-storage/actions/workflows/go.yml)
```suggestion
[![codecov](https://codecov.io/gh/open-source-firmware/go-tcg-storage/graph/badge.svg?token=VYR0YKPUD5)](https://codecov.io/gh/open-source-firmware/go-tcg-storage)
```

2025-05-15 13:34 UTC, matfax commented on cmd/sedlockctl/cmd.go
> +	Password   string `required:"" short:"p" env:"PASS" type:"password" help:"SID Password"`
By using the same embed, `-p` would have to be sacrificed in `sedlockctl` because they are embedded with prefixes in `gosedctl`, making the short duplicates. `kong` so far hasn't introduced a *smart* or idiomatic way to deal with such a use case overlap.

2025-05-15 13:59 UTC, matfax commented
> I noticed you have one commit changing `open-source-firmware` to `matfax` in pathes and an commit reverting these changes. Can you remove these back and forth changes please.

They won't be visible in the squashed version. That's why I favor this method. Only the changes listed under the "Files changed" will be introduced into your git tree. I couldn't find any leftovers from the package change there. They only exist because I copied my main branch at some point so to port the features into this PR. And this package port only exists so that I could easily reference the package for inclusion in u-root, unrelated to this repo.

> When done removing the two commits mentioned above, you can squash the feature with its tests and chore commits into two commits (one for feature/test, one for chores)

I have adopted the changes you suggested. For preview, I also removed the `p` short for the `sedlockctl` password (addressing [this](https://github.com/open-source-firmware/go-tcg-storage/pull/114#discussion_r2081646950)). Please let me know which approach you favor, having `-p` and `-a` (for hash) in instances where only a single `PasswordEmbed` is embedded, or just the same *"shortless"* embed in all instances for simplicity.

Please also note the LICENSE amendment for the modified kong mapper. MIT and BSD-3 should be compatible, but I separately included it to be on the safe side.

One that's clarified, I will squash the changes per your recommendation, separating the different commit types.

2025-05-16 09:34 UTC, ChriMarMe commented
I will not put squash-commits onto main. Please rebase/refactor/cleanup the PR history without squash-commits. 

Aside from that: LGTM.

2025-05-16 12:56 UTC, matfax commented
Just to clarify the difference:

* `Squash and "merge"` takes all the commits from a PR and combines (“squashes”) them into a single commit (or a few, if you squash manually) before merging into the main branch. This flattens the commit history, so you lose the individual commit details from the PR branch.
* `Merge` using a merge commit or rebase preserves the full commit history from the PR branch, combining it into the main branch with a single merge commit. This keeps all the individual commits visible in the main branch history.

It sounds like you’re looking for a clean, linear commit history on the main branch, which is exactly what GitHub’s “Squash and merge” option does when merging a PR. With this option enabled in the repo settings, you can squash all PR commits into one (or a few, if you squash manually) right from the GitHub UI—no need to force-push a squashed branch.

So, I’ve already squashed and force-pushed the branch for you, but in the future, you can just use the “Squash and merge” button on GitHub when merging PRs to achieve the same result. This keeps the main branch history tidy without losing the context of the PR.

LGTM!

2025-05-19 07:25 UTC, ChriMarMe reviewed
Auto squash leads to cobbled up commit messages, I have no insight how you use git/github. I know that I can allow the squash and merge method, but as said above: it leads to messy commit messaged. We don't want that.

This change is a little too big for one commit. Reworking the device path handling is indepenedent from the sha512 support. The handling of passwords/hashes is independent from the sha512 support.

Please seperate the commit into the amount of commits that would allow to revert these changes independently.

2025-05-25 14:45 UTC, matfax commented
I've separated the features; with the additional change that the resolver now asks twice for a password in `gosedctl`` because I've noticed in my testing that typos need to be ruled out somehow when setting new passwords.

I've also tested `initial-setup`, but `load-pba` seems to have issues on my test machine, so I've decided to just leave out the `kong.FileContentsFlag` for now, even though that's unlikely the cause because the file contents are read properly. Though it fits into the scope of this kong refactoring, I'll open a separate PR so it can be investigated separately.

2025-05-26 09:34 UTC, mynetz commented
> I've also tested `initial-setup`, but `load-pba` seems to have issues on my test machine, so I've decided to just leave out the `kong.FileContentsFlag` for now, even though that's unlikely the cause because the file contents are read properly. Though it fits into the scope of this kong refactoring, I'll open a separate PR so it can be investigated separately.

@matfax Did not review your PR (yet). Do you think this is connected to some work you did or general? I encountered an issue with one of my drives with `load-pba`. The `s.ExecuteMethod(mc)` returns with `ErrTPerClosedSession`. Using `sedutil-cli` works.

Comparing the code suggests that we use a different sealing for the block size. `sedutil-cli` uses a max of: 
https://github.com/Drive-Trust-Alliance/sedutil/blob/6270fb0e3c110572d96936a473b5e0d21a39884d/Common/DtaDevOpal.cpp#L1132-L1133

We use `maxSize := s.ControlSession.TPerProperties.MaxComPacketSize - 200` which in case of my drive was higher than MAX_BUFFER_LENGTH. After I limited the value (modified the code) it worked.

I did not yet consult the standard in detail or investigated this on the different drives I have. Once I have I raise a issue or PR with a proposal. Right now I am just curious what you have observed.

2025-05-27 12:39 UTC, matfax commented
@mynetz I'll comment on it in #130.

2025-05-28 12:43 UTC, merged