The great refactor
open-source-firmware/go-tcg-storage pull request #88
Opened 2022-04-22 11:14 UTC by ChriMarMe

The purpose of this PR is to rework parts of the library to make it more maintainable and easier to extend with additional features.

2022-05-10 09:21 UTC, ChriMarMe commented
I warp this PR up here, because anything related to a rework of sessions creates a behemoth of a PR and requires changes all over the repository. 

From this point on I'll only take reviews and suggestions for minor changes in the PR. Additional topics shall be brought forward via Issues.

2022-05-23 13:23 UTC, MDr164 requested changes
Looks mostly good to me. Just a few nitpicks here and there.

2022-05-23 13:23 UTC, MDr164 commented on cmd/sedlockctl/main.go
> +	tcg "github.com/open-source-firmware/go-tcg-storage/pkg/core"
Is there a reason to import it as `tcg` here and in tcgdiskstat just as core?

2022-05-23 13:23 UTC, MDr164 commented on pkg/core/table/admin.go
>  	// TODO: This is taken from the Opal spec, not sure how to dynamically find it...
You removed the code that this comment belonged to but not the comment itself, was that intended?

2022-05-23 13:23 UTC, MDr164 commented on pkg/core/uid/methods.go
> +package uid
Missing License header above

2022-05-23 13:23 UTC, MDr164 commented on pkg/core/uid/rows.go
> +package uid
Missing License header above

2022-05-23 13:23 UTC, MDr164 commented on pkg/core/uid/tables.go
> +package uid
Missing License header above

2022-05-23 13:23 UTC, MDr164 commented on pkg/core/uid/uid.go
> +package uid
Missing License header above

2022-05-23 13:23 UTC, MDr164 commented on README.md
> +    // otherwise you will need to figure out the ComID and
Weird indentation here

2022-05-23 13:23 UTC, MDr164 commented on pkg/core/core.go
> +func FindComID(d drive.DriveIntf, d0 *Level0Discovery) (ComID, ProtocolLevel, error) {
Now that this function is exported, it should get a code comment stating its functionality.

2022-05-23 14:08 UTC, merged